### ISSUE TITLE
[bug] Just says end impersonation

### ISSUE THREAD

**Issue by laggis** [Alexr03/TCAdminImpersonation#1]
When i press the end impersonation this popup and its only says end impersonation not impersonation as
![bug](https://user-images.githubusercontent.com/18127838/95929114-79e88f00-0dc3-11eb-8c5b-9c251f0fdf33.png)

**Comment by Alexr03** [comment]
Hi,
Open the website on the machine and do the same actions there so I can see the real error.

**Comment by laggis** [comment]
> Hi,
> Open the website on the machine and do the same actions there so I can see the real error.

Sorry for slow response was sleeping works perfect on localhost not via ip thoe

**Comment by Alexr03** [comment]
Clear your cookies. And try incognito mode. Does it work then?
